### ISSUE TITLE
remove overriden implementation of generateKey metod in SimpleKeyGenerator template

### ISSUE THREAD

**Issue by nitheesh121** [arunmr1980/spring-ws-project-creator#12]

**Comment by arunmr1980** [comment]
@nitheesh121 Is SimpleKeyGenerator no longer required ?

**Comment by nitheesh121** [comment]
The class is required , but it will not have a method until the client decides to override it. So in template we can keep the class which implements the IDGenerator interface from commons package , so it will get the default implementation

**Comment by arunmr1980** [comment]
Okay

**Comment by arunmr1980** [comment]
Done
